-- Add User.mobile. Backfilled from the matching Student.mobile (joined on
-- students.userId = users.id). Admins have no Student row, so their
-- mobile stays NULL — they continue to log in with their `studentId`
-- (e.g. SMC-ADMIN-001). The unique index is partial so the many admin
-- rows with NULL mobile don't conflict with each other.

ALTER TABLE "users" ADD COLUMN "mobile" TEXT;

-- Backfill: copy mobile from each user's linked student profile. If two
-- distinct users somehow ended up with the same mobile we keep the
-- lowest user.id (lexical) and NULL the others, so the unique index
-- can be applied safely. In practice this never happens because the
-- student admit flow already rejects duplicate mobiles.
UPDATE "users" u
SET    "mobile" = s."mobile"
FROM   (
  SELECT "userId", "mobile",
         ROW_NUMBER() OVER (PARTITION BY "mobile" ORDER BY "userId") AS rn
  FROM   "students"
  WHERE  "isDeleted" = false
) s
WHERE  u."id" = s."userId"
  AND  s."rn" = 1;

-- For the (rare) rows where two distinct users previously shared the
-- same mobile, blank the duplicate user rows so the unique index can
-- be applied. The Student row still holds the canonical mobile for
-- display.
UPDATE "users" u
SET    "mobile" = NULL
FROM   (
  SELECT "userId", "mobile",
         ROW_NUMBER() OVER (PARTITION BY "mobile" ORDER BY "userId") AS rn
  FROM   "students"
  WHERE  "isDeleted" = false
) s
WHERE  u."id" = s."userId"
  AND  s."rn" > 1;

CREATE INDEX "users_mobile_idx" ON "users"("mobile");

-- Partial unique index: only ACTIVE (non-deleted) users that have a
-- mobile are constrained to be unique. Admins without a mobile share
-- the same NULL slot without conflict.
CREATE UNIQUE INDEX "users_mobile_active_unique"
  ON "users"("mobile")
  WHERE "mobile" IS NOT NULL AND "isDeleted" = false;

-- Per-enrollment Student ID. Generated by the application using the
-- course's hscBatch + name via `generateStudentId`. Legacy rows get a
-- unique value here too — collision handled by retrying the generator
-- when we wire it on the application side. For the backfill we use a
-- deterministic seed per row so any conflicts can be manually resolved.

ALTER TABLE "student_courses" ADD COLUMN "studentCourseId" TEXT;

-- Backfill: assign a unique studentCourseId to each existing enrollment.
-- We use a CTE + window function to pick a unique 3-digit suffix per
-- (hscBatch, yearDigit) prefix. Existing data: each existing
-- User.studentId was already unique-per-prefix (the application
-- generator enforced that), so we don't have to worry about clashes.
-- We copy the linked User.studentId value as a sensible default and
-- fall back to a generated id where the user has none.
UPDATE "student_courses" sc
SET    "studentCourseId" = u."studentId"
FROM   "students" s
JOIN   "users" u ON u."id" = s."userId"
WHERE  sc."studentId" = s."id"
  AND  sc."studentCourseId" IS NULL;

-- For any rows still null after the copy (shouldn't happen with the
-- current data shape, but kept for safety), leave NULL — the column is
-- nullable until the next migration wires the strict non-null
-- constraint. The application enforces non-null at write time.
CREATE UNIQUE INDEX "student_courses_studentCourseId_key"
  ON "student_courses"("studentCourseId")
  WHERE "studentCourseId" IS NOT NULL;
